# Prediction using Bagging with Random Forest

# Challenge

## Bagging with Random Forest

In [ ]:
# general imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from numpy import mean
from numpy import std
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
# data imports
# Read CSV train data file into DataFrame
data_df1=pd.read_csv('/Users/vamseemuppavarapu/Archanaa_NIIT/Bagging/DS2_C5_S6_AllRent_Data_Challenge.csv')
data_df1.head()
data_df=data_df1

In [ ]:
# evaluation imports


from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

In [ ]:
data_df.columns

Index(['Unnamed: 0', 'bathrooms', 'bedrooms', 'building_id', 'created',
       'description', 'display_address', 'features', 'latitude', 'listing_id',
       'longitude', 'manager_id', 'photos', 'price', 'street_address',
       'interest_level'],
      dtype='object')

In [ ]:
data_df.dtypes

Unnamed: 0           int64
bathrooms          float64
bedrooms             int64
building_id         object
created             object
description         object
display_address     object
features            object
latitude           float64
listing_id           int64
longitude          float64
manager_id          object
photos              object
price                int64
street_address      object
interest_level      object
dtype: object

In [ ]:
data_df.head()

,Unnamed: 0,bathrooms,bedrooms,building_id,created,description,display_address,features,latitude,listing_id,longitude,manager_id,photos,price,street_address,interest_level
0,105408,1.0,0,0f9d07991ba14c82d3d368b72d90270a,04-04-2016 03:34,Gorgeous unit in one of the most genuinely cov...,230 Central Park South,"['Cats Allowed', 'Dogs Allowed', 'Doorman', 'E...",40.7672,6827153,-73.9802,932589de9230b697808216774fa26bd4,['https://photos.renthop.com/2/6821519_0a14cc2...,2800,230 Central Park South,high
1,110219,1.0,1,564d6f608f41e8d4a5e181c4e068e3d9,21-04-2016 20:40,Enormous 1 bedroom apartment in Murray Hill. F...,E 39th St,"['Cats Allowed', 'Dogs Allowed', 'Reduced Fee'...",40.7483,6908998,-73.9741,489ad933197469ae66acd1f7ce18f908,['https://photos.renthop.com/2/6908998_6b00895...,2100,243 E 39th St,high
2,56113,1.0,1,69790fbf0bf7e22b1d0ebc721cf0f633,14-05-2016 05:44,"This 1 bedroom, 1 bathroom spacious apartment ...",E 25th St.,"['Elevator', 'Furnished', 'Hardwood Floors']",40.7399,7013774,-73.9812,792c0f1ad1431397c65db3e69b770928,['https://photos.renthop.com/2/7013774_e7ead5d...,3000,217 E 25th St.,high
3,37765,1.0,2,d0234abbc01a982d54e8d446acc03405,05-06-2016 03:37,SPECTACULAR2 BEDROOM APARTMENT IN LUXURY 24HR ...,West 34th Street,"['Doorman', 'Elevator', 'Dishwasher', 'Hardwoo...",40.7530,7113518,-73.9958,eb5a6c4c2eb6f3e2a085c477afd5a815,['https://photos.renthop.com/2/7113518_d234153...,3000,360 West 34th Street,high
4,67397,1.0,2,a36895b9975c6991ca0fa1d9a99023a1,26-05-2016 05:36,NO FEE.. Newly Reno XL Convertible 2 Br .. Pri...,East 72nd Street,"['Dining Room', 'Doorman', 'Elevator', 'Fitnes...",40.7695,7071666,-73.9603,0a6ba20b892ed61df751420934d1ab51,['https://photos.renthop.com/2/7071666_4f81618...,3300,200 East 72nd Street,high

In [ ]:
#Checking null values
data_df.isnull().sum()

Unnamed: 0           0
bathrooms            0
bedrooms             0
building_id          0
created              0
description        286
display_address     34
features             0
latitude             0
listing_id           0
longitude            0
manager_id           0
photos               0
price                0
street_address       5
interest_level       0
dtype: int64

In [ ]:
data_df['created']=data_df['created'].astype('category')
data_df['interest_level']=data_df['interest_level'].astype('category')
#data_df['price'] = data_df['price'].str[:4]

In [ ]:
data_df["created"] = data_df["created"].str.slice(6,10)

In [ ]:
data_df['created']

0       2016
1       2016
2       2016
3       2016
4       2016
        ...
9866    2016
9867    2016
9868    2016
9869    2016
9870    2016
Name: created, Length: 9871, dtype: object

In [ ]:
data_df['created']=data_df['created'].astype('int64')

In [ ]:
label_encoder = preprocessing.LabelEncoder()
# Encode labels in column 'interest_level'.
data_df['interest_level_encode']= label_encoder.fit_transform(data_df['interest_level'])
data_df['interest_level_encode'].unique()

array([0, 1, 2])

In [ ]:
X=data_df[['bathrooms','bedrooms','created','latitude','longitude','price']]
y=data_df['interest_level']

### Train Test split

In [ ]:

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=100)
print('Size of training dataset: ', x_train.shape)
print('Size of test dataset: ', x_test.shape)

Size of training dataset:  (6909, 6)
Size of test dataset:  (2962, 6)

### Baseline Regression model

## Decision Tree

In [ ]:
# define the model
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

classifier_rf = DecisionTreeClassifier(random_state=42, max_depth=5)
classifier_rf.fit(x_train, y_train)
y_pred1 = classifier_rf.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_test, y_pred1, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.72      0.09      0.16       247
     class 1       0.72      0.96      0.82      2024
     class 2       0.39      0.14      0.21       691

    accuracy                           0.69      2962
   macro avg       0.61      0.40      0.40      2962
weighted avg       0.65      0.69      0.62      2962

## RandomForest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(random_state=42, n_jobs=-1, max_depth=5, n_estimators=100, oob_score=True)
classifier_rf.fit(x_train, y_train)
y_pred2 = classifier_rf.predict(x_test)

In [ ]:
from sklearn.metrics import classification_report
target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_test, y_pred2, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.84      0.06      0.12       247
     class 1       0.69      1.00      0.82      2024
     class 2       0.62      0.01      0.01       691

    accuracy                           0.69      2962
   macro avg       0.72      0.36      0.32      2962
weighted avg       0.69      0.69      0.57      2962

### Bootstrap sampling of data into different subsets and evaluating

Bootstrapping is a resampling 'with replacement' of the original dataset. It corresponds to sampling n out of n data points with replacement uniformly at random from the original dataset. n is the number of data points in the original dataset.there are also data points from the original dataset that are never selected to appear in a bootstrap sample

In [ ]:
def bootstrap_sample(data, target):
    # Indices corresponding to a sampling with replacement of the same sample
    # size than the original data
    bootstrap_indices = rng.choice(np.arange(target.shape[0]), size=target.shape[0], replace=True)
    # In pandas, we need to use `.iloc` to extract rows using an integer
    # position index:
    data_bootstrap = data.iloc[bootstrap_indices]
    target_bootstrap = target.iloc[bootstrap_indices]
    return data_bootstrap, target_bootstrap

In [ ]:
X=data_df[['bathrooms','bedrooms','created','latitude','longitude','price']]
y=data_df['interest_level']

In [ ]:
data_train, data_test, target_train, target_test = train_test_split(X, y, test_size=0.3,random_state=100)

In [ ]:
#import random as rng
from sklearn.metrics import accuracy_score
bag_of_trees = []
target_names = ['class 0', 'class 1', 'class 2']
rng = np.random.RandomState(1)
n_bootstraps = 3

for bootstrap_idx in range(n_bootstraps):
    # draw a bootstrap from the original data
    tree = DecisionTreeClassifier(max_depth=3, random_state=1)
    data_bootstrap, target_bootstrap = bootstrap_sample(data_train, target_train)
    tree.fit(data_bootstrap, target_bootstrap)
    bag_of_trees.append(tree)

In [ ]:
for tree_idx, tree in enumerate(bag_of_trees):
    tree_predictions = tree.predict(data_test)
    print("Bootstrap"+str(tree_idx),classification_report(target_test, tree_predictions, target_names=target_names))

Bootstrap0               precision    recall  f1-score   support

     class 0       0.50      0.06      0.11       247
     class 1       0.70      0.99      0.82      2024
     class 2       0.48      0.04      0.07       691

    accuracy                           0.69      2962
   macro avg       0.56      0.36      0.33      2962
weighted avg       0.63      0.69      0.58      2962

Bootstrap1               precision    recall  f1-score   support

     class 0       0.82      0.06      0.11       247
     class 1       0.69      1.00      0.81      2024
     class 2       0.00      0.00      0.00       691

    accuracy                           0.69      2962
   macro avg       0.50      0.35      0.31      2962
weighted avg       0.54      0.69      0.56      2962

Bootstrap2               precision    recall  f1-score   support

     class 0       0.00      0.00      0.00       247
     class 1       0.70      0.96      0.81      2024
     class 2       0.35      0.10      0.15       691

    accuracy                           0.68      2962
   macro avg       0.35      0.35      0.32      2962
weighted avg       0.56      0.68      0.59      2962

In [ ]:
bag_of_trees = []
target_names = ['class 0', 'class 1', 'class 2']
rng = np.random.RandomState(1)
n_bootstraps = 3

for bootstrap_idx in range(n_bootstraps):
    # draw a bootstrap from the original data
    tree = RandomForestClassifier(max_depth=3, random_state=1)
    data_bootstrap, target_bootstrap = bootstrap_sample(data_train, target_train)
    tree.fit(data_bootstrap, target_bootstrap)
    #ypred=tree.predict(data_test)
    bag_of_trees.append(tree)

In [ ]:
for tree_idx, tree in enumerate(bag_of_trees):
    tree_predictions = tree.predict(data_test)
    print("Bootstrap"+str(tree_idx),classification_report(target_test, tree_predictions, target_names=target_names))

Bootstrap0               precision    recall  f1-score   support

     class 0       0.00      0.00      0.00       247
     class 1       0.68      1.00      0.81      2024
     class 2       0.00      0.00      0.00       691

    accuracy                           0.68      2962
   macro avg       0.23      0.33      0.27      2962
weighted avg       0.47      0.68      0.55      2962

Bootstrap1               precision    recall  f1-score   support

     class 0       1.00      0.00      0.01       247
     class 1       0.68      1.00      0.81      2024
     class 2       0.00      0.00      0.00       691

    accuracy                           0.68      2962
   macro avg       0.56      0.33      0.27      2962
weighted avg       0.55      0.68      0.56      2962

Bootstrap2               precision    recall  f1-score   support

     class 0       0.00      0.00      0.00       247
     class 1       0.69      1.00      0.81      2024
     class 2       0.45      0.01      0.01       691

    accuracy                           0.68      2962
   macro avg       0.38      0.34      0.28      2962
weighted avg       0.57      0.68      0.56      2962

### Conclusion